### ISSUE TITLE
why am i also met this question

### ISSUE THREAD

**Issue by DavidWillie1106** [isLinXu/YOLOv5_Efficient#1]
'Namespace' object has no attribute 'noval' and 'Namespace' object has no attribute 'freeze'

**Comment by isLinXu** [comment]
In order to facilitate the positioning of this problem, perhaps you can describe the error in more detail

**Comment by DavidWillie1106** [comment]
Traceback (most recent call last):
  File "C:/Users/22183/Downloads/YOLOv5_Efficient-main/YOLOv5_Efficient-main/yolov5_master/train.py", line 965, in <module>
    train_main(opt)
  File "C:/Users/22183/Downloads/YOLOv5_Efficient-main/YOLOv5_Efficient-main/yolov5_master/train.py", line 773, in train_main
    train(opt.hyp, opt, device, callbacks)
  File "C:/Users/22183/Downloads/YOLOv5_Efficient-main/YOLOv5_Efficient-main/yolov5_master/train.py", line 74, in train
    opt.resume, opt.nosave, opt.workers, opt.freeze,opt.noval
AttributeError: 'Namespace' object has no attribute 'freeze'

noval也一样，如果我删除这两个参数就会显示参数缺失，我想保留他们两个然后改好这个问题

**Comment by DavidWillie1106** [comment]
大佬方便的话加个q交流一下吧   2056103495
